<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>flags_game</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Pages\Shared\Components\Edit\EditViewComponent.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Pages\Shared\Components\Edit\EditViewComponent.cs">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Pages\Shared\Components\FlagList\FlagListViewComponent.cs">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
