// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using flags_game.Models;

#nullable disable

namespace flags_game.Migrations
{
    [DbContext(typeof(FlagAppDbContext))]
    [Migration("20240612223832_Population")]
    partial class Population
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("flags_game.Models.Flag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("population")
                        .HasColumnType("INTEGER");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("flags");
                });

            modelBuilder.Entity("flags_game.Models.FlagTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FlagId");

                    b.HasIndex("TagId");

                    b.ToTable("flagTags");
                });

            modelBuilder.Entity("flags_game.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("flags_game.Models.FlagTag", b =>
                {
                    b.HasOne("flags_game.Models.Flag", "Flag")
                        .WithMany("flagTags")
                        .HasForeignKey("FlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("flags_game.Models.Tag", "Tag")
                        .WithMany("flagTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flag");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("flags_game.Models.Flag", b =>
                {
                    b.Navigation("flagTags");
                });

            modelBuilder.Entity("flags_game.Models.Tag", b =>
                {
                    b.Navigation("flagTags");
                });
#pragma warning restore 612, 618
        }
    }
}
